@rootUrl = http://localhost:8000/api/v1/

### GET
GET {{rootUrl}}users

### GET
GET {{rootUrl}}posts
### POST
POST {{rootUrl}}users
Content-Type: application/json

{
  "id": 4,
  "username": "Sir.Testsalot",
  "email": "tests@yoohoo.net",
  "role": "user",
  "birth_date": "01/01/2000",
  "gender": "male",
  "pfp_image_url": "https://picsum.photos/id/11/200/200"
}

### PATCH
PATCH {{rootUrl}}users/4
Content-Type: application/json

{
  "pfp_image_url": "https://picsum.photos/id/11/200/200"
}

### DELETE
DELETE {{rootUrl}}users/1
