@rootUrl = http://localhost:8000/api/v1/

### GET
GET {{rootUrl}}users

### POST
POST {{rootUrl}}users
Content-Type: application/json

{
  "username": "Sir.Testsalot",
  "email": "tests@yoohoo.net",
  "role": "user",
  "birth_date": "01/01/2000",
  "gender": "male",
  "pfp_image_url": "https://picsum.photos/id/11/200/300"
}

### PATCH
PATCH {{rootUrl}}users/1
Content-Type: application/json

{
  "username": "Sir.Testedalot"
}

### DELETE
DELETE {{rootUrl}}users/1
