name: RetrieveDeployments
on:
  push:
    branches:
      - main
jobs:
  accessRenderEndpoint:
    runs-on: ubuntu-latest
    environment: Render
    steps:
      - name: Fetch Render Deployments
        run: >-
          curl 
            --request GET \
            --url "https://api.render.com/v1/services/$RENDER_SERVICE_KEY/deploys?limit=20" \
            --header "accept: application/json" \
            --header "authorization: Bearer $RENDER_API_KEY"
